language: cpp
os: linux
dist: focal
jobs:
  include:

#   ubuntu focal fossa 20.04
#   gcc 9 is the default on bionic
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - valgrind
            - cppcheck
            - doxygen
            - cmake
      env: CHECK="true"

before_install:
  - echo "Starting before_install"
  - echo $CC
  - echo $LANG
  - echo $LC_ALL
  - set -e
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      eval "${MATRIX_EVAL}";
      if [ -n "$MATRIX_EVAL" ] && [ "$TRAVIS_COMPILER" != "clang" ]; then
        sudo apt-get install -y $CC;
      fi;
    fi

before_script:
  - echo "Starting before_script"
  - mkdir -p build || echo "Failed to mkdir build"
  - cd build || echo "Failed to cd build"
  - cmake .. || echo "Failed to run cmake"

script:
  - echo "Starting script"
  - make
  # when using bionic, Travis seems to ignore the "addons" section, so installing the packages with apt-get...
  - if [ -n "$CHECK" ]; then
      if [ "$TRAVIS_DIST" = "bionic" ]; then
        sudo apt-get install -y valgrind cppcheck doxygen;
      fi;
      make distcheck;
      if type cppcheck &> /dev/null ; then cppcheck --error-exitcode=1 --quiet *.h *.c tests/ ; fi;
    fi
